// src/app/experience-list/experience-list.component.ts
import { Component, Input, OnInit } from '@angular/core';
import { IExperienceItem } from './model/experience-list-item';

@Component({
  selector: 'mtg-experience-list',
  template: `
    <div class="my-12 flex flex-col space-y-12">
      <mtg-experience-item *ngFor="let exp of experienceItems; let i = index;" [experienceItem]="exp" [index]="i"></mtg-experience-item>
    </div>
  `,
  styles: [
  ]
})
export class ExperienceListComponent implements OnInit {

  @Input() experienceItems: IExperienceItem[] = [];

  constructor() { }

  ngOnInit(): void {
  }

}

// components/experience-list/experience-list.tsx
import React from 'react';
import { IExperienceItem } from './model/experience-list-item';
import ExperienceItem from './experience-item';

interface ExperienceListProps {
    experienceItems: readonly IExperienceItem[];
}

const ExperienceList = ({ experienceItems }: ExperienceListProps): JSX.Element => {

    return (
        <>
            <div className="my-12 flex flex-col space-y-24">
                {experienceItems.map((item, index) => (
                    <ExperienceItem key={`${item.title}-${item.startDate}`} title={item.title} description={item.description} index={index} startDate={item.startDate} endDate={item.endDate}></ExperienceItem>
                ))}
            </div>
        </>
    );
}

export default ExperienceList;
